[
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=7AnYDwAAQBAJ&hl=&source=gbs_api",
		},
		etag: "MEL0PTZCZ+k",
		id: "7AnYDwAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: { textSnippet: "You probably use websites every day, but have you ever thought about building them? With the help of this book, now you can!" },
		selfLink: "https://www.googleapis.com/books/v1/volumes/7AnYDwAAQBAJ",
		volumeInfo: {
			allowAnonLogging: true,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Freelance_Web_Developer_101.html?hl=&id=7AnYDwAAQBAJ",
			categories: [Array],
			contentVersion: "0.1.2.0.preview.1",
			description:
				"You probably use websites every day, but have you ever thought about building them? With the help of this book, now you can! In this exceptional step-by-step guide, you’ll learn what web development is all about, which resources will help you master it, and how you can build stunning and interactive websites. After instructing you on how to create your own personal web portfolio, the author will take you through all the major web development languages and technologies, including the following: • HTML • CSS • JavaScript • Bootstrap and jQuery • PHP and MySQL • WordPress Each of these chapters contains best practices and tips for success as well as a “Show Your Skills” section with practical and fun project ideas for you to apply what you’re learning. For example, “Write a JavaScript program that will run the game Chutes and Ladders thousands of time and determine the minimum, maximum, and average number of turns to win.” Lastly, you’ll find out how to transform your newfound hobby into a profitable career by becoming a freelance web developer. The author will share tips for perfecting your portfolio and finding clients, especially through the popular freelancing website Upwork. If you’ve ever been curious about web development but didn’t know where to start, this book is for you! Come and embrace both your creativity and logic by delving into the wonderful world of web development! About the Expert: Liz Kazandzhy is a passionate web developer who also greatly enjoys writing and editing. As the daughter of a software engineer, she has always had a knack for technology, so when she stumbled upon web development in 2016, it was love at first keystroke. She studied it voraciously and began building websites related to her personal interests, like RandomScriptureVerse.com. In time, she started branching out and building websites for others, like JonathanWhitlockArt.com. Liz currently lives in Orem, UT, with her husband Vlad and two energetic young daughters, Katya and Sophia. In the rare moments when the kids are asleep and the housework is done, she enjoys reading, writing, and developing websites. HowExpert publishes quick 'how to' guides on all topics from A to Z by everyday experts.",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=7AnYDwAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 73,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=7AnYDwAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=1&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2019-04-12",
			publisher: "HowExpert",
			readingModes: [Object],
			subtitle: "How to Start, Grow, and Succeed in Freelance Web Development from A to Z",
			title: "Freelance Web Developer 101",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "NONE",
			country: "NG",
			embeddable: false,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "NO_PAGES",
			webReaderLink: "http://play.google.com/books/reader?id=d-UezgEACAAJ&hl=&source=gbs_api",
		},
		etag: "qTpjVt+uG4w",
		id: "d-UezgEACAAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet: "At the end of this book, for your final project,you will build your own website. How To Be A Web Developer In 90 Days shares the code of a dynamic, innovative website.",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/d-UezgEACAAJ",
		volumeInfo: {
			allowAnonLogging: false,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/How_to_Be_a_Web_Developer_in_90_Days.html?hl=&id=d-UezgEACAAJ",
			contentVersion: "preview-1.0.0",
			description:
				"Be a Web Developer In 90 Days! Go from Beginner to Expert. *Easy Web development skills Book for Beginners*Step by Step guide - how to become a web developer*Become a web developer in 90 days*Java developer guide *Learn css web design Are you working at your dream job? What would you do if I told you I have my dream job? After working almost 20 years in corporate America, I figured out what career makes me happy. It's true, some people actually love their jobs! I can proudly say I am one of them. I am a Web Developer. I've been professionally coding websites from scratch for the last seven years. I freaking love coding! I recall when I would randomly ask people if they love their jobs. I was always puzzled when people said that they genuinely loved what they did for a living. Don't get me wrong, I had a plush sales career making six figures, a company car, corporate credit card and flexible hours but I was still unhappy. I dreaded Mondays. It was during the Covid-19 Pandemic that it hit me. What better time than now to help others transition into a new career? Our new normal requires a career that you can work from virtually anywhere. And a career that's in high demand. That's a win/win.The pandemic taught us a lot of things and one of them being that nothing is for certain. With millions of individuals losing their jobs due to Covid-19, now is the time to share my coding expertise and innovation with the world. I am just the person to teach you how to code because I too was once a beginner. I didn't major in technology or computer science. But I did go from beginner to expert and so can you. I currently own a successful creative design firm that specializes in cutting-edge web design, mobile apps and branding. You are going to enjoy this book because I have made coding fun by doing something that has never been done before. I've included animations that explain daily lessons. You will also receive a free 15 minute live chat with a Certified Web Developer. Plus, you can learn at your own pace. If you need additional help, there's an option to attend live online classes. At the end of this book, for your final project,you will build your own website. How To Be A Web Developer In 90 Days shares the code of a dynamic, innovative website. This code includes the features and functions that can easily be used as the foundation to build your clients' website. This book provides the blueprint to your new career. Are you ready to change your future? Let's gooooo!",
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=d-UezgEACAAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 329,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=d-UezgEACAAJ&dq=WEB+DEVEL&hl=&cd=2&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2020-11-18",
			readingModes: [Object],
			subtitle: "Web Development Skills",
			title: "How to Be a Web Developer in 90 Days",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=Fp3jCwAAQBAJ&hl=&source=gbs_api",
		},
		etag: "G4o5E3cxMiA",
		id: "Fp3jCwAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet:
				"A one-stop guide to the essentials of web development including popular frameworks such as jQuery, Bootstrap, AngularJS, and Node.js About This Book Understand the essential elements of HTML, CSS, and JavaScript, including how and when to ...",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/Fp3jCwAAQBAJ",
		volumeInfo: {
			allowAnonLogging: true,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Web_Developer_s_Reference_Guide.html?hl=&id=Fp3jCwAAQBAJ",
			categories: [Array],
			contentVersion: "0.5.5.0.preview.3",
			description:
				"A one-stop guide to the essentials of web development including popular frameworks such as jQuery, Bootstrap, AngularJS, and Node.js About This Book Understand the essential elements of HTML, CSS, and JavaScript, including how and when to use them Walk through three of the best and most popular web development frameworks – jQuery, Bootstrap, and AngularJS References for any function you will need in your day-to-day web development Who This Book Is For This book is perfect for beginners but more advanced web developers will also benefit. Laid out so you can refer to as much or as little as you need to, with this book you can exhaustively explore essential concepts for modern web developers. What You Will Learn Explore detailed explanations of all the major HTML elements and attributes, illustrated with examples Take a deep dive into CSS properties and functions and master their usage Find clear, concise descriptions of JavaScript syntax and expressions Recognize various JavaScript design patterns and learn the basics of JavaScript object-orientated programming Implement the latest ECMAScript 6 for client-side scripting in your web applications Discover new ways to develop your website's front end quickly and easily using Bootstrap Write JavaScript extensibly using jQuery-JavaScript's feature-rich library Delve into the key Node.js modules used in JavaScript server-side programming Access AngularJS 's important modules, controllers, directives, and services quickly In Detail This comprehensive reference guide takes you through each topic in web development and highlights the most popular and important elements of each area. Starting with HTML, you will learn key elements and attributes and how they relate to each other. Next, you will explore CSS pseudo-classes and pseudo-elements, followed by CSS properties and functions. This will introduce you to many powerful and new selectors. You will then move on to JavaScript. This section will not just introduce functions, but will provide you with an entire reference for the language and paradigms. You will discover more about three of the most popular frameworks today—Bootstrap, which builds on CSS, jQuery which builds on JavaScript, and AngularJS, which also builds on JavaScript. Finally, you will take a walk-through Node.js, which is a server-side framework that allows you to write programs in JavaScript. Style and approach This book is an easy-to-follow, comprehensive reference guide. Each topic, function, or element is listed methodically along with parameters, return values, and descriptions. Examples are also included to help you put the concepts to use quickly in the real world.",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=Fp3jCwAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 838,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=Fp3jCwAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=3&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2016-03-28",
			publisher: "Packt Publishing Ltd",
			readingModes: [Object],
			title: "Web Developer's Reference Guide",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=nSKoY9oHdlYC&hl=&source=gbs_api",
		},
		etag: "ON9+++zyG1E",
		id: "nSKoY9oHdlYC",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: { textSnippet: "A complete guide for web designers and developers who want to begin building and administering sites with WordPress." },
		selfLink: "https://www.googleapis.com/books/v1/volumes/nSKoY9oHdlYC",
		volumeInfo: {
			allowAnonLogging: false,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/WordPress_for_Web_Developers.html?hl=&id=nSKoY9oHdlYC",
			categories: [Array],
			contentVersion: "1.3.3.0.preview.3",
			description: "A complete guide for web designers and developers who want to begin building and administering sites with WordPress.",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=nSKoY9oHdlYC&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 356,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=nSKoY9oHdlYC&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=4&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2013-06-25",
			publisher: "Apress",
			readingModes: [Object],
			subtitle: "An Introduction for Web Professionals",
			title: "WordPress for Web Developers",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=6Ze7DQAAQBAJ&hl=&source=gbs_api",
		},
		etag: "yg6n73I0VBg",
		id: "6Ze7DQAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet:
				"In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript.",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/6Ze7DQAAQBAJ",
		volumeInfo: {
			allowAnonLogging: true,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Understanding_ECMAScript_6.html?hl=&id=6Ze7DQAAQBAJ",
			categories: [Array],
			contentVersion: "2.3.3.0.preview.3",
			description:
				"ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript. Every chapter is packed with example code that works in any JavaScript environment so you’ll be able to see new features in action. You’ll learn: –How ECMAScript 6 class syntax relates to more familiar JavaScript concepts –What makes iterators and generators useful –How arrow functions differ from regular functions –Ways to store data with sets, maps, and more –The power of inheritance –How to improve asynchronous programming with promises –How modules change the way you organize code Whether you’re a web developer or a Node.js developer, you’ll find Understanding ECMAScript 6 indispensable on your journey from ECMAScript 5 to ECMAScript 6.",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=6Ze7DQAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 353,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=6Ze7DQAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=5&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2016-08-16",
			publisher: "No Starch Press",
			readingModes: [Object],
			subtitle: "The Definitive Guide for JavaScript Developers",
			title: "Understanding ECMAScript 6",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=9yxOi4b73QIC&hl=&source=gbs_api",
		},
		etag: "k6ExzghSGDg",
		id: "9yxOi4b73QIC",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet:
				"... <b>Web Developer</b> 2005 Express Edition Recent Projects complete Open : Create : Web Sit Web S Getting Started Create a Personal Web Site Create a Web Site Create a Web Service Download Additional Starter Kits Community Resources for Visual Web&nbsp;...",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/9yxOi4b73QIC",
		volumeInfo: {
			allowAnonLogging: false,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Wrox_s_ASP_NET_2_0_Visual_Web_Developer.html?hl=&id=9yxOi4b73QIC",
			categories: [Array],
			contentVersion: "1.2.2.0.preview.1",
			description:
				"This Starter Kit serves as an entry-level introduction centered around prebuilt projects that developers can easily deploy and customize for their own sites Explains how to build good basic Web sites, including design and architecture, for users who plan to build more complex sites in the future Details the key site features that beginners like to implement, including catalogs, shopping carts, images, and secure site sections The authors use very little code, but where coding is needed, they feature the simple Visual Basic language The CD-ROM includes Visual Web Developer 2005 Express Edition",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=9yxOi4b73QIC&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 314,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=9yxOi4b73QIC&pg=PA20&dq=WEB+DEVEL&hl=&cd=6&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2006-01-18",
			publisher: "John Wiley & Sons",
			readingModes: [Object],
			title: "Wrox's ASP.NET 2.0 Visual Web Developer 2005 Express Edition Starter Kit",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "NONE",
			country: "NG",
			embeddable: false,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED_FOR_ACCESSIBILITY",
			viewability: "NO_PAGES",
			webReaderLink: "http://play.google.com/books/reader?id=hovpPKK8vL4C&hl=&source=gbs_api",
		},
		etag: "tuQYkDNPsFk",
		id: "hovpPKK8vL4C",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet:
				"Methods for using HTML5 to make Web pages even more interactive and dynamic are also provided. Shorten development time and sharpen your programming skills with help from this practical guide.",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/hovpPKK8vL4C",
		volumeInfo: {
			allowAnonLogging: true,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Web_Developer_s_Cookbook.html?hl=&id=hovpPKK8vL4C",
			categories: [Array],
			contentVersion: "2.11.13.0.preview.2",
			description:
				"300+ Ready-to-Use PHP, JavaScript, and CSS Solutions Web Developer's Cookbook contains more than 300 PHP, JavaScript, and CSS recipes you can use right away to create interactive Web content. All of the solutions are fully documented and their functionality clearly explained, along with customization tips. The recipes include HTML examples and screen shots showing exactly how to apply them in real-world situations. Methods for using HTML5 to make Web pages even more interactive and dynamic are also provided. Shorten development time and sharpen your programming skills with help from this practical guide. Filled with tested recipes for: PHP Text processing * Image handling * Content management * Forms and user input * Internet * Chat and messaging * MySQL, sessions, and cookies * APIs, RSS, and XML * Incorporating JavaScript JavaScript Core functionality * Location and dimensions * Visibility * Movement and animation * Chaining and interaction * Menus and navigation * Text effects * Audio and visual effects * Cookies, Ajax, and security * Forms and validation * Solutions to common problems CSS Manipulating objects * Text and typography * Menus and navigation * Page layout * Visual effects * Dynamic objects * Dynamic text and typography * Incorporating JavaScript * Superclasses",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=hovpPKK8vL4C&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 994,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=hovpPKK8vL4C&q=WEB+DEVEL&dq=WEB+DEVEL&hl=&cd=7&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2012-04-23",
			publisher: "McGraw Hill Professional",
			readingModes: [Object],
			title: "Web Developer's Cookbook",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=9ZTlCgAAQBAJ&hl=&source=gbs_api",
		},
		etag: "H08WORRTqzk",
		id: "9ZTlCgAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: { textSnippet: "In five separate sections, this book shows you how to protect against viruses, DDoS attacks, security breaches, and other nasty intrusions." },
		selfLink: "https://www.googleapis.com/books/v1/volumes/9ZTlCgAAQBAJ",
		volumeInfo: {
			allowAnonLogging: false,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Security_for_Web_Developers.html?hl=&id=9ZTlCgAAQBAJ",
			categories: [Array],
			contentVersion: "0.1.1.0.preview.1",
			description:
				"As a web developer, you may not want to spend time making your web app secure, but it definitely comes with the territory. This practical guide provides you with the latest information on how to thwart security threats at several levels, including new areas such as microservices. You’ll learn how to help protect your app no matter where it runs, from the latest smartphone to an older desktop, and everything in between. Author John Paul Mueller delivers specific advice as well as several security programming examples for developers with a good knowledge of CSS3, HTML5, and JavaScript. In five separate sections, this book shows you how to protect against viruses, DDoS attacks, security breaches, and other nasty intrusions. Create a security plan for your organization that takes the latest devices and user needs into account Develop secure interfaces, and safely incorporate third-party code from libraries, APIs, and microservices Use sandboxing techniques, in-house and third-party testing techniques, and learn to think like a hacker Implement a maintenance cycle by determining when and how to update your application software Learn techniques for efficiently tracking security threats as well as training requirements that your organization can use",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=9ZTlCgAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 382,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=9ZTlCgAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=8&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2015-11-10",
			publisher: '"O\'Reilly Media, Inc."',
			readingModes: [Object],
			subtitle: "Using JavaScript, HTML, and CSS",
			title: "Security for Web Developers",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=9OfIDQAAQBAJ&hl=&source=gbs_api",
		},
		etag: "1953tWotXqc",
		id: "9OfIDQAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: { textSnippet: "This brief book is an easy-to-digest introduction to the key concepts of web development." },
		selfLink: "https://www.googleapis.com/books/v1/volumes/9OfIDQAAQBAJ",
		volumeInfo: {
			allowAnonLogging: false,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/Introducing_Web_Development.html?hl=&id=9OfIDQAAQBAJ",
			categories: [Array],
			contentVersion: "1.3.3.0.preview.3",
			description:
				"This brief book is an easy-to-digest introduction to the key concepts of web development. Understand the concepts of the web and how they apply to static and dynamic websites. See how HTML and CSS are used to create the bones of the web. Concisely presented through four key concept chapters, Introducing Web Development will enable you to get a clear understanding of how web development works. What You Will Learn How the web works and interacts with websites What static and dynamic websites are and how they work How the static parts of a website are coded using HTML and CSS Who This Book Is For Anyone who wants to understand the basics of web development.",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=9OfIDQAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 99,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=9OfIDQAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=9&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2016-12-22",
			publisher: "Apress",
			readingModes: [Object],
			title: "Introducing Web Development",
		},
	},
	{
		accessInfo: {
			accessViewStatus: "SAMPLE",
			country: "NG",
			embeddable: true,
			epub: [Object],
			pdf: [Object],
			publicDomain: false,
			quoteSharingAllowed: false,
			textToSpeechPermission: "ALLOWED",
			viewability: "PARTIAL",
			webReaderLink: "http://play.google.com/books/reader?id=n5vcDgAAQBAJ&hl=&source=gbs_api",
		},
		etag: "gwKtuyTo5Js",
		id: "n5vcDgAAQBAJ",
		kind: "books#volume",
		saleInfo: { country: "NG", isEbook: false, saleability: "NOT_FOR_SALE" },
		searchInfo: {
			textSnippet:
				"Develop your real-time MEAN application efficiently using a combination of MongoDB, Express, Angular, and Node About This Book Construct a fully-functional MEAN application by using its components along with the best third-party modules ...",
		},
		selfLink: "https://www.googleapis.com/books/v1/volumes/n5vcDgAAQBAJ",
		volumeInfo: {
			allowAnonLogging: true,
			authors: [Array],
			canonicalVolumeLink: "https://books.google.com/books/about/MEAN_Web_Development.html?hl=&id=n5vcDgAAQBAJ",
			categories: [Array],
			contentVersion: "0.1.2.0.preview.3",
			description:
				"Develop your real-time MEAN application efficiently using a combination of MongoDB, Express, Angular, and Node About This Book Construct a fully-functional MEAN application by using its components along with the best third-party modules Harness the power of the JavaScript ecosystem to effectively run, build, and test your MEAN application Gain a deep, practical understanding of real-time web application development through real-world examples Who This Book Is For If you are a JavaScript developer who is interested in building modern web applications using MongoDB, Express, Angular 2, and Node 5.0, then this book is for you. You only need knowledge of JavaScript development. What You Will Learn Use MongoDB to store and retrieve your application's data Connect your Express application to MongoDB and use the Mongoose module Manage your users' authentication and offer them diverse login options using Passport Structure and use an Angular 2 application in your MEAN project Use Socket.io to create real-time communication between your client and server Test your application's Express and Angular 2 entities In Detail The MEAN stack is a collection of the most popular modern tools for web development that helps you build fast, robust, and maintainable web applications. Starting with the MEAN core frameworks, this pragmatic guide will explain the key concepts of each framework, how to set them up properly, and how to use popular modules to connect it all together. By following the real-world examples shown in this tutorial, you will scaffold your MEAN application architecture, add an authentication layer, and develop an MVC structure to support your project development. You will learn the best practices of maintaining clear and simple code and will see how to avoid common pitfalls. Finally, you will walk through the different tools and frameworks that will help expedite your daily development cycles. Watch how your application development grows by learning from the only guide that is solely orientated towards building a full, end-to-end, real-time application using the MEAN stack! Style and approach This comprehensive guide covers every part of the MEAN stack, and focuses on the gestalt power of the apps they can create through practical, real-world examples",
			imageLinks: [Object],
			industryIdentifiers: [Array],
			infoLink: "http://books.google.com/books?id=n5vcDgAAQBAJ&dq=WEB+DEVEL&hl=&source=gbs_api",
			language: "en",
			maturityRating: "NOT_MATURE",
			pageCount: 367,
			panelizationSummary: [Object],
			previewLink: "http://books.google.com/books?id=n5vcDgAAQBAJ&printsec=frontcover&dq=WEB+DEVEL&hl=&cd=10&source=gbs_api",
			printType: "BOOK",
			publishedDate: "2016-11-30",
			publisher: "Packt Publishing Ltd",
			readingModes: [Object],
			title: "MEAN Web Development",
		},
	},
];
